config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#show'

  resources :games, only: %i[show new create update], param: :uid do
    member do
      post :close
      post :start_next_round
      post :restart_current_round
    end

    resources :players, only: %i[show new create update destroy] do
      resources :technologies, only: %i[create destroy], param: :key
      resources :objectives, only: [], param: :key do
        collection do
          post :score_public
          post :score_secret
        end
      end
    end

    resources :rounds, only: %i[create] do
      member do
        post :pick_strategy_cards
        post :finish_action_phase
        post :finish_status_phase
        post :pick_agenda_cards
        post :finish_agenda_phase
        post :reveal_objective
      end
    end
  end

  resources :technologies, only: %i[show], param: :key
end

app/models/game.rb
class Game < ApplicationRecord
  PLAYERS_COUNT_RANGE = (3..6).freeze

  class PlayerScores
    def self.load(hash)
      transform_key_and_values_to_integer(hash || {})
    end

    def self.dump(hash)
      hash.to_hash
    end

    def self.transform_key_and_values_to_integer(hash)
      hash.each_with_object({}) { |(k, v), h| h[k.to_i] = v.to_i }
    end
  end

  include SimpleUid
  include AASM

  serialize :map
  serialize :player_scores, PlayerScores

  has_many :rounds, dependent: :destroy
  has_many :players, dependent: :destroy
  belongs_to :winner, class_name: 'Player', optional: true
  belongs_to :custodian_owner, class_name: 'Player', optional: true

  before_create :set_started_at

  aasm do
    state :preparing, initial: true
    state :active
    state :closed, before_enter: :set_ended_at

    event :close do
      transitions from: %i[preparing active], to: :closed
    end

    event :start do
      transitions from: %i[preparing], to: :active, guard: :ready_to_start?
    end

    event :restart do
      transitions from: :active, to: :preparing, guard: :no_more_rounds?
    end
  end

  def playtime
    (ended_at || Time.current) - started_at
  end

  def player_score(player)
    player_scores.fetch(player.id, 0)
  end

  def revealed_objectives
    @revealed_objectives ||= rounds.flat_map(&:revealed_objectives)
  end

  def revealed_agenda_cards
    @revealed_agenda_cards ||= rounds.flat_map(&:revealed_agenda_cards)
  end

  def custodian_taken?
    custodian_owner.present?
  end

  def current_round
    rounds.order(index: :asc).last
  end

  def current_round_number
    current_round&.index || 0
  end

  def restart_current_round
    current_round&.destroy
    restart! if may_restart?
  end

  def next_round_number
    current_round_number + 1
  end

  def create_next_round(revealed_objectives:, speaker:)
    round = rounds.build(index: next_round_number, speaker: speaker)
    round.revealed_objectives = revealed_objectives
    round.save!

    start! if preparing?
  end

  def to_param
    uid
  end

  def enough_players?
    PLAYERS_COUNT_RANGE.include?(players.count)
  end

  def player_limit_reached?
    players.count >= PLAYERS_COUNT_RANGE.max
  end

  def strategy_cards_per_player
    players.count < 5 ? 2 : 1
  end

  private

  def no_more_rounds?
    rounds.none?
  end

  def ready_to_start?
    enough_players?
  end

  def set_ended_at
    self.ended_at = Time.zone.now
  end

  def set_started_at
    self.started_at = Time.zone.now
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = find_game
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(new_game_params)

    if @game.save
      redirect_to game_url(@game)
    else
      render :new
    end
  end

  def update
    game = find_game
    game.update(update_game_params)

    redirect_to game
  end

  def close
    game = find_game
    game.close!

    redirect_to root_url
  end

  def start_next_round
    game = find_game
    objectives_for_round = new_rounds_params[:public_objectives].map { |key| PublicObjective.find_by(key: key) }
    speaker = game.players.find(new_rounds_params[:speaker_id])
    game.create_next_round(revealed_objectives: objectives_for_round, speaker: speaker)

    redirect_to game
  end

  def restart_current_round
    game = find_game
    game.restart_current_round

    redirect_to game
  end

  private

  def update_game_params
    params.require(:game).permit([{ player_scores: {} }, :custodian_owner_id])
  end

  def new_rounds_params
    params.require(:game).permit([{ public_objectives: [] }, :speaker_id])
  end

  def find_game
    Game.find_by!(uid: params[:uid])
  end

  def new_game_params
    params.require(:game).permit(:name, :map, :victory_points)
  end
end

app/views/games/states/_active.html.erb
<section class="mb-l">
  <h2>Round <%= game.current_round_number %>: <%= t("activerecord.attributes.round.aasm_state.#{game.current_round.aasm_state}") %></h2>

  <% if game.current_round.finished? %>
    <h3>Revealed Public Objective from previous Status Phase</h3>

    <%= form_with model: @game, url: start_next_round_game_path(game), method: :post, class: "form-columns" do |f| %>
      <%= render "games/form/select_objective", form: f, game: game, objectives: available_public_objectives_for_game(game) %>
      <%= render "games/form/select_speaker", form: f, game: game %>

      <%= f.submit "Start Next Round" %>
    <% end %>
  <% else %>
    <%= render "rounds/states/#{game.current_round.aasm_state}", game: game, round: game.current_round %>
  <% end %>
</section>

app/views/games/states/_closed.html.erb
<section class="mb-l">
<dl>
  <dt>Winner:</dt>
  <dd><%= link_to_if game.winner.present?, game.winner&.name || ??, game.winner %></dd>
  <dt>Started at:</dt>
  <dd><%= l(game.started_at, format: :short) %></dd>
  <dt>Endet at:</dt>
  <dd><%= l(game.ended_at, format: :short) %></dd>
  <dt>Playtime:</dt>
  <dd><%= distance_of_time_in_words(game.playtime) %></dd>
</dl>
</section>

app/views/games/states/_preparing.html.erb
<section class="mb-l">
  <% if !game.player_limit_reached? %>
    <%= link_to "Add another Player", new_game_player_path(@game) %>
  <% end %>

  <% if !game.enough_players? %>
    <p>Please add more players.</p>
  <% else %>
    <h2>Reveal first two stage 1 objectives</h2>
    <%= form_with model: game, url: start_next_round_game_path(game), method: :post, class: "form-columns" do |f| %>
      <%= render "games/form/select_objective", form: f, game: game, objectives: PublicObjective.stage_one %>
      <%= render "games/form/select_objective", form: f, game: game, objectives: PublicObjective.stage_one %>
      <%= render "games/form/select_speaker", form: f, game: game %>

      <%= f.submit "Start Game!", disabled: !game.may_start? %>
    <% end %>
  <% end %>
</section>