config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#show'

  resources :games, only: %i[show new create update], param: :uid do
    member do
      post :close
      post :start_next_round
      post :restart_current_round
    end

    resources :players, only: %i[show new create update destroy] do
      resources :technologies, only: %i[create destroy], param: :key
      resources :objectives, only: [], param: :key do
        collection do
          post :score_public
          post :score_secret
        end
      end
    end

    resources :rounds, only: %i[create] do
      member do
        post :pick_strategy_cards
        post :finish_action_phase
        post :finish_status_phase
        post :pick_agenda_cards
        post :finish_agenda_phase
        post :reveal_objective
      end
    end
  end

  resources :technologies, only: %i[show], param: :key
end

app/models/round.rb
class Round < ApplicationRecord
  include AASM

  belongs_to :game
  belongs_to :speaker, class_name: 'Player'
  has_many :player_stats, dependent: :destroy
  has_many :player, through: :player_stats

  attribute :revealed_objectives, :value_object, default: []
  # NOTE: The Agenda Card `Classified Document Leaks` allows declaring any SecretObjective to be public
  validates :revealed_objectives, array_inclusion: { in: (SecretObjective.all + PublicObjective.all) }

  attribute :revealed_agenda_cards, :value_object, default: []
  validates :revealed_agenda_cards, array_inclusion: { in: AgendaCard.all }

  before_create :set_started_at

  aasm do
    state :strategy_phase, initial: true
    state :action_phase
    state :status_phase
    state :agenda_phase
    state :finished, before_enter: :set_ended_at

    event :start_action_phase do
      transitions from: :strategy_phase, to: :action_phase
    end

    event :start_status_phase do
      transitions from: :action_phase, to: :status_phase
    end

    event :start_agenda_phase do
      transitions from: :status_phase, to: :agenda_phase, guard: :custodian_taken?
    end

    event :finish do
      transitions from: %i[status_phase agenda_phase], to: :finished
    end
  end

  private

  def custodian_taken?
    game.custodian_taken?
  end

  def set_started_at
    self.started_at = Time.zone.now
  end

  def set_ended_at
    self.ended_at = Time.zone.now
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :load_current_game
  before_action :find_round

  def pick_strategy_cards
    round_params[:strategy_card_picks].each do |(player_id, strategy_card_keys)|
      @round.player_stats.create!(
        player: @current_game.players.find(player_id),
        picked_strategy_cards: strategy_card_keys.map { |key| StrategyCard.find_by(key: key) }
      )
    end
    @round.start_action_phase!

    redirect_to @current_game
  end

  def finish_action_phase
    @round.start_status_phase!

    redirect_to @current_game
  end

  def finish_status_phase
    if @round.may_start_agenda_phase?
      @round.start_agenda_phase!
    else
      @round.finish!
    end

    redirect_to @current_game
  end

  def pick_agenda_cards
    @round.revealed_agenda_cards = round_params[:agenda_cards].map { |key| AgendaCard.find_by(key: key) }
    @round.save!

    redirect_to @current_game
  end

  def reveal_objective
    round = find_round
    params[:game][:public_objectives].each do |key|
      round.revealed_objectives << PublicObjective.find_by_key(key)
    end
    round.save!

    redirect_to @current_game
  end

  def finish_agenda_phase
    @round.finish!

    redirect_to @current_game
  end

  private

  def find_round
    @round ||= @current_game.rounds.find(params[:id]) # rubocop:disable Naming/MemoizedInstanceVariableName
  end

  def new_player_params
    params.require(:player).permit(:name, :faction).merge(game: @current_game)
  end

  def round_params
    params.require(:round).permit(strategy_card_picks: {}, agenda_cards: [])
  end

  def load_current_game
    @current_game ||= Game.find_by!(uid: params[:game_uid]) # rubocop:disable Naming/MemoizedInstanceVariableName
  end
end

app/views/rounds/states/_action_phase.html.erb
<section class="mb-s">
  <% unless @game.custodian_taken? %>
    <h3>Score Custodian for Player</h3>
    <%= form_with scope: @game, method: :patch, class: "form-columns form-slim" do |f| %>
      <%= f.select :custodian_owner_id, @game.players.map { |p| [p.name, p.id] } %>
      <%= f.submit "Save" %>
    <% end %>
  <% end %>
</section>

<section class="mb-l">
  <%= button_to "Finish Action Phase", finish_action_phase_game_round_path(game, round) %>
</section>

app/views/rounds/states/_agenda_phase.html.erb
<section class="mb-s">
  <ol>
    <li>Reveal first Agenda, Vote, Resolve</li>
    <li>Reveal second Agenda, Vote, Resolve</li>
    <li>Ready Planets</li>
  </ol>
</section>

<section class="mb-s">
  <% if round.revealed_agenda_cards.blank? %>
    <h3>Reveal two Agenda Cards</h3>
    <%= form_with model: round, url: pick_agenda_cards_game_round_path(game, round), method: :post, class: "form-columns" do |f| %>
      <div class="select">
        <label for="first_agenda">First Agenda</label>
        <%= text_field_tag :"round[agenda_cards][]", "", list: "agenda_cards", required: true, autocomplete: "off", id: "first_agenda" %>
      </div>
      <div class="select">
        <label for="second_agenda">Second Agenda</label>
        <%= text_field_tag :"round[agenda_cards][]", "", list: "agenda_cards", required: true, autocomplete: "off", id: "second_agenda" %>
      </div>

      <datalist id="agenda_cards">
        <%= options_from_collection_for_select available_agenda_cards_for_game(game), :key, :title %>
      </datalist>

      <%= f.submit "Save Agenda Cards" %>
    <% end %>
  <% else %>
    <h3>Revealed Agenda Cards</h3>
    <% round.revealed_agenda_cards.each do |agenda_card| %>
      <%= render agenda_card %>
    <% end %>

    <h3>Reveal additional Public Objective</h3>
    <%= form_with model: round, url: reveal_objective_game_round_path(game, round), method: :post, class: "form-columns form-slim" do |f| %>
      <%= render "games/form/select_objective", form: f, game: game, objectives: available_additional_public_objectives_for_agenda_phase(game) %>
     <%= f.submit "Reveal" %>
    <% end %>
  <% end %>
</section>

<section class="mb-l">
  <%= button_to "Finish Round", finish_agenda_phase_game_round_path(game, round) %>
</section>

app/views/rounds/states/_status_phase.html.erb
<section class="status-phase-overview mb-s">
  <ol>
    <li>Score Objectives</li>
    <li>Reveal Public Objective</li>
    <li>Draw Action Cards (Initiative Order)</li>
    <li>Remove Command Tokens</li>
    <li>Gain and Redistribute Command Tokens</li>
    <li>Ready Planets</li>
    <li>Repair Units</li>
    <li>Return Strategy Cards</li>
  </ol>
</section>

<section class="mb-l">
  <%= button_to "Finish Status Phase", finish_status_phase_game_round_path(game, round) %>
</section>

app/views/rounds/states/_strategy_phase.html.erb
<section class="mb-l">
  <%= form_with model: round, url: pick_strategy_cards_game_round_path(game, round), method: :post, class: "form-columns" do |f| %>
    <% game.players.each_with_index do |player| %>
      <% game.strategy_cards_per_player.times do |i| %>
        <div class="select">
          <label for="strategy_card_<%= player.id %>_<%= i %>"><%= player.name %></label>
          <%= select_tag :"round[strategy_card_picks[#{player.id}]][]", options_from_collection_for_select(strategy_cards, :key, :title_for_select), id: "strategy_card_#{player.id}_#{i}" %>
        </div>
      <% end %>
    <% end %>

    <%= f.submit "Save Picks" %>
  <% end %>
</section>