config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#show'

  resources :games, only: %i[show new create update], param: :uid do
    member do
      post :close
      post :start_next_round
      post :restart_current_round
    end

    resources :players, only: %i[show new create update destroy] do
      resources :technologies, only: %i[create destroy], param: :key
      resources :objectives, only: [], param: :key do
        collection do
          post :score_public
          post :score_secret
        end
      end
    end

    resources :rounds, only: %i[create] do
      member do
        post :pick_strategy_cards
        post :finish_action_phase
        post :finish_status_phase
        post :pick_agenda_cards
        post :finish_agenda_phase
        post :reveal_objective
      end
    end
  end

  resources :technologies, only: %i[show], param: :key
end

app/models/player.rb
class Player < ApplicationRecord
  include SimpleUid

  belongs_to :game
  has_many :player_stats, dependent: :restrict_with_exception
  has_many :rounds, through: :player_stats

  validates :name, presence: true
  validates :seat_number, presence: true

  attribute :faction, :value_object
  validates :faction, presence: true

  attribute :technologies, :value_object, default: []
  validates :technologies, array_inclusion: { in: Technology.all }

  def faction=(faction)
    super

    self.technologies = faction.starting_tech
  end

  def scored_objective?(objective)
    player_stats.any? { |player_stat| player_stat.scored_public_objectives.include?(objective) }
  end

  def scored_secret_objectives
    @scored_secret_objectives ||= player_stats.flat_map(&:scored_secret_objectives)
  end

  def can_score_another_secret_objective?
    scored_secret_objectives.count < 3
  end

  def owns_castodian?
    game.custodian_owner == self
  end

  def currently_speaker?
    game.current_round.speaker == self
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :load_current_game

  def show
    @player = @current_game.players.find(params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(new_player_params)

    if @player.save
      redirect_to @current_game
    else
      render :new
    end
  end

  def destroy
    player = @current_game.players.find(params[:id])
    player.destroy!

    redirect_to @current_game
  end

  private

  def player_params
    params.require(:player).permit(:name, :faction, :seat_number)
  end

  def new_player_params
    player_params.merge(
      faction: Faction.find_by(key: player_params[:faction]),
      game: @current_game
    )
  end

  def load_current_game
    @current_game ||= Game.find_by!(uid: params[:game_uid]) # rubocop:disable Naming/MemoizedInstanceVariableName
  end
end

app/views/players/new.html.erb
<h1>Add new Player</h1>

<%= form_with model: @player, url: game_players_path(@current_game) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <%= f.label :faction %>
  <%= f.collection_select :faction, available_factions_for_game(@current_game), :first, :last %>
  <%= f.label :seat_number %>
  <%= f.select :seat_number, available_seats_for_game(@current_game) %>

  <%= f.submit %>
<% end %>

app/views/players/show.html.erb
<div class="faction-title">
  <%= image_tag_for_faction(@player.faction) %>
  <h2><%= @player.faction.title %></h2>
  <% if @current_game.active? && @player.owns_castodian? %>
    <%= image_tag "custodian.png", class: "custodian-token" %>
  <% end %>
</div>

<p>Played by <%= @player.name %></p>

<% if @current_game.active? && (@current_game.current_round.action_phase? || @current_game.current_round.status_phase?) %>
  <section class="mb-s">
    <h2>Score Public Objective</h2>
    <% @current_game.revealed_objectives.each do |objective| %>
      <div class="player-objective <%= @player.scored_objective?(objective) ? "player-objective--scored" : "" %>">
        <%= render objective %>
        <div class="player-objective-actions">
          <% if !@player.scored_objective?(objective) %>
            [<%= link_to "score 🚀!", score_public_game_player_objectives_path(@current_game, @player, objective_key: objective.key), method: :post %>]
          <% end %>
        </div>
      </div>
    <% end %>
  </section>

  <section class="mb-s">
    <% if @player.scored_secret_objectives.any? %>
      <h2>Scored Secret Objective</h2>
      <% @player.scored_secret_objectives.each do |objective| %>
        <%= render objective %>
      <% end %>
    <% else %>
      <p>None yet</p>
    <% end %>

    <% if @player.can_score_another_secret_objective? %>
      <datalist id="secret_objective">
        <%= options_from_collection_for_select available_secret_objectives_for_player(@player), :key, :title %>
      </datalist>

      <%= form_with url: score_secret_game_player_objectives_path(@current_game, @player), method: :post, class: "form-columns form-slim" do |f| %>
        <div class="select">
          <label for="secret_objectives">Secret Objective</label>
          <%= f.text_field :objective_key, list: "secret_objective", required: true, autocomplete: "off" %>
        </div>
        <%= f.submit "Score" %>
      <% end %>
    <% end %>
  </section>
<% end %>

<% if @current_game.active? && @player.currently_speaker? %>
  <h3>[Currently Speaker]</h3>
<% end %>

<section class="mb-l">
  <h3>Technologies</h3>
  <% if @player.technologies.any? %>
    <% @player.technologies.group_by(&:type).each do |tech_type, technologies| %>
      <% technologies.each do |technology| %>
        <div class="player-technology">
          <%= render technology %>
          <div class="player-technology-actions">
            [<%= link_to "undo?", game_player_technology_path(@current_game, @player, technology.key), method: :delete %>]
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    No technologies yet. Add starting Technologies.
  <% end %>

  <h3>Add Tech</h3>
  <%= form_with scope: :technology, url: game_player_technologies_path(@current_game, @player), class: "form-columns" do |f| %>
    <div class="select">
      <%= f.label :key, "Which tech?" %>
      <%= f.text_field :key, list: "technologies", autocomplete: "off" %>
      <datalist id="technologies">
        <%= options_from_collection_for_select available_tech_for_player(@player), :key, :title %>
      </datalist>
    </div>

    <%= f.submit "Add" %>
  <% end %>
</section>